spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: index_routh
          uri: lb://index-mybatis
          namespace: 50b36829-3afc-4ed4-9f11-b79ed8ca032b
          group: INDEX_GROUP
          predicates:
            - Path=/test/test1