spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/policies_information?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
  data:
    redis:
      database: 0
      host: 192.168.23.129
      port: 6379
      password: linyinjie123
      connect-timeout: 1000
  mail:
    host: smtp.qq.com
    username: 2323572223@qq.com
    password: uqoktuaibpvtecci
    default-encoding: UTF-8
    port: 587
    protocol: smtp

mybatis:
  mapper-locations: classpath:mapper/*.xml